### ISSUE TITLE
怎么没有拍照和视频录制呢

### ISSUE THREAD

**Issue by zcwk** [Faceunity/FULiveDemoDroid#1]
怎么没有拍照和视频录制呢，如何实现呢

**Comment by ray007great** [comment]
demo目前还没有拍照和录制功能，日后可能会添上。

至于实现，给出一个参考：
拍照，如果通过使用返回的texture，通过glReadPixel把像素内容读出来，然后保存到本地；如果通过使用返回的nv21数组，你可以把这个nv21数组转换成一个图片格式需要的然后保存到本地。
录制视频，如果通过返回的texture，你可以采用硬编；如果通过返回的nv21数组，你可以采用软编。

FU SDK目前还不提供视频编码相关的服务，如果采用硬编的话，您可以参考下grafika这个项目，里面有一个录制camera返回的texture的例子。

这个issue我就先关掉了。

**Comment by zcwk** [comment]
请问texture返回的数据是不是已经是合成后的呢。是不是有那些小道具的比如小兔子的那些动画的呢

**Comment by ray007great** [comment]
是的，并且返回的texture类型为TEXTURE_2D.
