### ISSUE TITLE
surfaceView 渲染美颜

### ISSUE THREAD

**Issue by lybryant** [Faceunity/FULiveDemoDroid#11]
请问下使用surfaceView在输入数据处理后怎么渲染上美颜的呢？

**Comment by TuJHgithub** [comment]
SurfaceView是能够实现渲染faceunty的美颜的，但是需要自己维护GL环境（faceunty的美颜很多api是基于opengl的），这种方法比较麻烦不推荐呢么做。
实际上系统的GLSurfaceView就是做了相应的工作（如果有特殊需求必须使用SurfaceView，可以参考GLSurfaceView的源码），一般比较推荐直接使用GLSurfaceView。
