### ISSUE TITLE
How to create prop?

### ISSUE THREAD

**Issue by dangbadat** [Faceunity/FULiveDemoDroid#13]
You can instruct me to create prop or provide documentation and tools.

**Comment by TuJHgogo** [comment]
https://github.com/Faceunity/FULiveDemoDroid/tree/dev#%E9%81%93%E5%85%B7%E5%88%9B%E5%BB%BA%E9%94%80%E6%AF%81%E4%B8%8E%E5%88%87%E6%8D%A2
