### ISSUE TITLE
无法进行人脸识别

### ISSUE THREAD

**Issue by ZLdeSpirit** [Faceunity/FULiveDemoDroid#2]
没办法显示效果，问题为未识别到人脸，能够提供测试密钥吗？

**Comment by ray007great** [comment]
请问是没有测试证书authpack吗？测试证书可以联系下我司技术支持。

人脸无法识别的问题是指从进入界面一开始就无法识别，还是指过了一段时间后无法识别？如果是后者可以提供下控制台的大致log输出，可能是测试证书已经过期了。

**Comment by ZLdeSpirit** [comment]
我没有authpack，一开始就无法进行人脸识别，是因为没有证书的原因吗？

**Comment by ray007great** [comment]
对的，没有证书无法正常使用。
