### ISSUE TITLE
Migrating to AndroidX

### ISSUE THREAD

**Issue by tl-yen** [Faceunity/FULiveDemoDroid#30]
請把 demo project 從 support library 升級到 AndroidX
https://developer.android.com/jetpack/androidx/migrate?hl=zh-tw

**Comment by tl-shane** [comment]
@tl-yen 
<img width="410" alt="螢幕快照 2020-05-06 下午3 05 30" src="https://user-images.githubusercontent.com/50481790/81146527-0ee09400-8fab-11ea-8cea-2f686640f1db.png">

**Comment by isuperqiang** [comment]
> 請把 demo project 從 support library 升級到 AndroidX
> https://developer.android.com/jetpack/androidx/migrate?hl=zh-tw

已更新到 androidX

**Comment by kurtchen1988** [comment]
all set
