### ISSUE TITLE
相册选择一个视频，能否不渲染到屏幕，添加滤镜保存一个新的视频文件

### ISSUE THREAD

**Issue by timmy008** [Faceunity/FULiveDemoDroid#31]
FURenderer 这个方法 public int onDrawFrame(byte[] img, int w, int h) 是否支持，若支持需要怎么样把处理后的byte[]保存到文件

**Comment by isuperqiang** [comment]
> FURenderer 这个方法 public int onDrawFrame(byte[] img, int w, int h) 是否支持，若支持需要怎么样把处理后的byte[]保存到文件

请查阅文档

**Comment by kurtchen1988** [comment]
please refer to our document, thank you
