### ISSUE TITLE
在部分机型录制的视频会不断的闪屏，请问这个有没方案可以解决？

### ISSUE THREAD

**Issue by zsgfrtttt** [Faceunity/FULiveDemoDroid#37]
录制短视频的时候已经添加了如下代码，但部分机型还是会严重闪屏
mediaCaptureController.getMediaRecord().setCameraBufferNum(1);//防止低端机型闪屏

**Comment by isuperqiang** [comment]
> 录制短视频的时候已经添加了如下代码，但部分机型还是会严重闪屏
> mediaCaptureController.getMediaRecord().setCameraBufferNum(1);//防止低端机型闪屏

请问这发生在 fulivedemo 中么？

**Comment by zsgfrtttt** [comment]
> > 录制短视频的时候已经添加了如下代码，但部分机型还是会严重闪屏
> > mediaCaptureController.getMediaRecord().setCameraBufferNum(1);//防止低端机型闪屏
> 
> 请问这发生在 fulivedemo 中么？
是的

**Comment by isuperqiang** [comment]
> > > 录制短视频的时候已经添加了如下代码，但部分机型还是会严重闪屏
> > > mediaCaptureController.getMediaRecord().setCameraBufferNum(1);//防止低端机型闪屏
> > 
> > 
> > 请问这发生在 fulivedemo 中么？
> > 是的

可是 fulivedemo 中没有你发的代码

**Comment by kurtchen1988** [comment]
not valid issue
