### ISSUE TITLE
读取本地视频，用mediacodec解码后的视频帧作为输入

### ISSUE THREAD

**Issue by langxuelang** [Faceunity/FULiveDemoDroid#7]
读取本地视频，用mediacodec解码后的视频帧作为输入，但是发现，目前android上面mediacodec解码出来的yuv格式非常多，不一定是nv21格式的，这篇文章有详细市面上各种手机解码后的格式http://alumnus.caltech.edu/~heirich/styled-6/index.html。

我的问题是，faceu是否可以只输入纹理，然后就进行识别，而不用输入nv21的视频数据？

如果不可以，你们这边是否有mediacodec解码后数据转换为nv21的方案？

谢谢。

**Comment by AndroidInternal** [comment]
你好，开放一个只输入纹理的接口已经在计划内。

急着要的话可以联系技术支持，我们可以尽快发一个内部版本给你用上。

**Comment by langxuelang** [comment]
@AndroidInternal 好的，可否问下，只输入纹理版本效率方面和之前那种dual input方式是否有差别，差别大不大

**Comment by AndroidInternal** [comment]
会有差距，但不会太大，会和`dualinput`与`renderToNV21`的性能差距类似，我们后续应该会出对应接口的测试报告。

这个接口我们会用优化方案来做减少性能损失，所以要等一等。

**Comment by AndroidInternal** [comment]
新增接口fuRenderToTexture
