### ISSUE TITLE
字幕支持？

### ISSUE THREAD

**Issue by langxuelang** [Faceunity/FULiveDemoDroid#8]
您好，我们有一个添加字幕的需求，请问咱们的sdk里面是否可以有类似的支持的api

**Comment by AndroidInternal** [comment]
我们的道具定制程度很高。可以在到道具里添加字幕水印之类的东西。

**Comment by langxuelang** [comment]
@AndroidInternal 我们的字幕需要实时生产，道具可以做到在程序里面生成吗？
还有一个问题，就是道具是否可以不跟随人脸，而是在固定位置

**Comment by AndroidInternal** [comment]
可以的，道具和客户端代码可以实时交互，把要显示的字幕内容传给道具即可，可以联系下技术支持提供一下FUEditor工具及对应文档。

道具可以不跟随人脸。

**Comment by langxuelang** [comment]
@AndroidInternal 好的，谢谢

**Comment by AndroidInternal** [comment]
Sorry，仔细想了下，目前的道具只能贴图支持，如果您是实时写任何字体的话，目前的道具是不支持的。

所以只能您手动在我们返回的内容里自己画了，目前的sdk还没提供对应的api。

**Comment by langxuelang** [comment]
@AndroidInternal 可以留一个qq联系方式吗，想具体交流下

**Comment by AndroidInternal** [comment]
联系商务或者support邮箱下吧，会建一个技术支持群。
